### ISSUE TITLE
Język domyślny na start

### ISSUE THREAD

**Issue by madrypiotr** [madrypiotr/SDD#1]
Wszystko działa OK dopiero po wybraniu danego języka.
Na start, **jak również po "ręcznym" przeładowaniu**, klient widzi nazwy zmiennych (nawet ten zalogowany, który określił swój język w profilu).
Skoro użytkownik, klikając, otrzymuje pożądany efekt, to pewnie System "sam z siebie" będzie mógł to uczynić, trzeba mu to "powiedzieć" w kodzie.
## Trzeba spowodować, 
aby j.polski, który jest językiem domyślnym był faktycznie widziany "na dzień dobry".

Język domyślny jest zdefiowany w pliku: ... lib\constants.js 
```
LANGUAGES = {
    DEFAULT_LANGUAGE: "pl"
}
```
Natomiast po zalogowaniu już tylko język Użytkownika.

**Comment by MichalW** [comment]
Najlepiej ustawić domyślny język przy pierwszym załadowaniu strony:

należy stworzyć plik np: `client/lib/i18n.js` a w nim:
```
Meteor.startup(function () {
      TAPi18n.setLanguage('pl');
});
```

**Comment by MichalW** [comment]
Pozwolę sobie jeszcze zwrócić uwagę na Pana niezabezpieczone metody serwerowe:
Każdy (nawet niezalogowany) użytkownik może wykonać metodę np.:
```
Meteor.call('removeZespolRealizacyjnyDraft', {});
```
co spowoduje usunięcie pana dokumentów z bazy danych. 
Należałoby sprawdzać this.userId. 
Proponuję również dodać odpowiednie allow/deny:
http://docs.meteor.com/api/collections.html#Mongo-Collection-deny

**Comment by madrypiotr** [comment]
@MichalW 
**Dziękuję** za cenne sugestie!

Język domyślny już działa...

**Comment by madrypiotr** [comment]
Dziękuję.

Pomogło!

--
pm

----------------------------------------------------------------------------------------
W dniu 01.03.2017 o 13:25 Michał Wanat <notifications@github.com> pisze:
