### ISSUE TITLE
Nie działa przycisk Cancel

### ISSUE THREAD

**Issue by madrypiotr** [madrypiotr/SDD#6]
client\views\ustawienia\zgloszenieCzlonkow\add_honorowy.html

**Comment by MichalW** [comment]
W pliku SDD/client/views/ustawienia/zgloszenieCzlonkow/add_honorowy.js jest pusta funkcja:
```
'reset form':function(e){
}
```

trzeba by do niej dopisać coś w stylu:
```
$("#honorowyForm").reset();
```

**Comment by madrypiotr** [comment]
... "_coś w stylu_...", to było właściwe stwierdzenie, 
bo akurat `$("#honorowyForm").reset();`nie spełniło oczekiwań.
Natomiast **pomogło: `Router.go('listKwestia');`**
### @MichalW - dziękuję za odszukanie newralgicznego miejsca!
